[package]
name = "gba-macros"
version = "0.1.0"
authors = ["Ruin0x11 <ipickering2@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
quote = "0.6.8"
proc-macro2 = "0.4.20"

[dependencies.syn]
features = ["extra-traits", "full"]
version = "0.15.26"