[package]
name = "gba-examples"
version = "0.1.0"
authors = ["Ruin0x11 <ipickering2@gmail.com>"]
edition = "2018"

[dependencies]
boot = { path = "../boot" }
gba = { path = "../gba" }

[profile.release]
codegen-units = 1
debug = true
lto = true