[package]
name = "gba-examples"
version = "0.1.0"
authors = ["Ruin0x11 <ipickering2@gmail.com>"]
edition = "2018"

[dependencies]
gba-boot = { path = "../gba-boot" }
gba = { path = "../gba" }

[dev-dependencies]
panic-halt = "0.2.0"
